#update
#Tomcat config
server:
  port: 8080
  tomcat:
    max-http-post-size: 8192

#Redis config
spring:
  application:
    name: spring-boot-redis
  redis:
    host: 106.15.251.138
    port: 6379
#MySQL config
  datasource:
    url: jdbc:mysql://106.15.251.138:3306/weatherproject?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #RabbitMQ config
  rabbitmq:
    host: 106.15.251.138
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true  #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #手动模式
        concurrency: 1 #最小消费者数量
        max-concurrency: 2 #最大消费者数量
        retry:
          enabled: true #是否支持重试

#mapper4.0 config
mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.example.springboot.mapperbase.BaseMapper

#阿里短信验证
accessKeyId:
accessSecret: 



